import { createServer } from "node:http";
import { once } from "node:events";
import { WebSocket } from "ws";
import { expect, it } from "vitest";
import type { ServerFrame } from "cozygateway-contract";
import { AttachV1Ingress } from "../src/adapters/attach/ingress-v1.ts";
import type { AttachV1ServerFrame } from "../src/adapters/attach/protocol-v1.ts";
import { NativeBotDataPlane } from "../src/hermes-bridge/native-data-plane.ts";
import type { BotsSurface } from "../src/hermes-bridge/bridge.ts";
import { createApp } from "../src/http.ts";
import { openStorage } from "../src/storage.ts";

async function until(check: () => boolean): Promise<void> {
  const deadline = Date.now() + 2000;
  while (!check()) { if (Date.now() > deadline) throw new Error("Task ingress condition timed out"); await new Promise((resolve) => setTimeout(resolve, 5)); }
}

it("admits public direct chat through authenticated attach, then exposes one completed Task and replacement stream", async () => {
  const storage = openStorage(":memory:");
  let now = Date.now();
  storage.tasks.clock(() => now);
  const frames: ServerFrame[] = [];
  let presence = "absent";
  let plane: NativeBotDataPlane;
  const ingress = new AttachV1Ingress({ tokens: new Map([["peer-secret", "sage"]]), storage, now: () => now, events: { onEvent: (peer, frame) => plane.handle(peer, frame), onPresence: (_peer, state) => { presence = state; } }, log: () => {} });
  plane = new NativeBotDataPlane({ storage, ingress, now: () => now, control: {} as BotsSurface, nativeBots: ["sage"], chatSuggestion: "", broadcast: (frame) => frames.push(frame) });
  storage.tasks.observe((frame) => frames.push(frame));
  const server = createServer();
  server.on("upgrade", (request, socket, head) => ingress.handleUpgrade(request, socket, head));
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  if (address === null || typeof address === "string") throw new Error("missing test listener");
  let peer = new WebSocket(`ws://127.0.0.1:${address.port}/attach/v1`, { headers: { authorization: "Bearer peer-secret" } });
  const incoming: AttachV1ServerFrame[] = [];
  peer.on("message", (data) => incoming.push(JSON.parse(String(data)) as AttachV1ServerFrame));
  try {
    await once(peer, "open");
    peer.send(JSON.stringify({ kind: "hello", version: 2, instanceId: "test", capabilities: ["draft", "tools", "approvals"], resume: { eventSequence: 0, commandSequence: 0 } }));
    await until(() => incoming.some((frame) => frame.kind === "hello_ack"));
    const app = createApp({ storage, now: () => now, config: { name: "test", port: 0, dbPath: ":memory:", turnTimeoutSeconds: 0 }, gatewayInfo: { name: "test", version: "test", contract: "v1", capabilities: { "com.cozylabs.bots": 64 } }, bots: plane.surface(), presenceOf: () => "online", submitUserMessage: () => { throw new Error("unexpected core ingress"); }, interruptThread: () => "idle", resolveApproval: async () => "unknown", onDeviceRevoked: () => {}, flushTaskCommands: () => ingress.flushTaskCommands() });
    storage.createSetupCode("task-pair", Date.now() + 10000);
    const paired = await app.request("/pair", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ setupCode: "task-pair", deviceName: "phone" }) });
    expect(paired.status, await paired.clone().text()).toBe(200);
    const { deviceToken } = await paired.json() as { deviceToken: string };
    const request = (path: string, body?: object) => app.request(path, { headers: { authorization: `Bearer ${deviceToken}`, "content-type": "application/json" }, ...(body === undefined ? {} : { method: "POST", body: JSON.stringify(body) }) });
    const sent = await request("/bots/sage/chat/messages", { text: "Verify the requested outcome" });
    expect(sent.status).toBe(202);
    await until(() => incoming.some((frame) => frame.kind === "command" && frame.command.kind === "turn"));
    const turn = incoming.find((frame) => frame.kind === "command" && frame.command.kind === "turn");
    if (turn?.kind !== "command" || turn.command.kind !== "turn") throw new Error("missing dispatched turn");
    const { threadId, turnId } = turn.command;
    const listed = await (await request("/bots/sage/tasks")).json() as { tasks: { taskId: string; state: string }[] };
    expect(listed.tasks).toHaveLength(1);
    expect(listed.tasks[0]?.state).toBe("queued");
    const taskId = listed.tasks[0]!.taskId;
    peer.send(JSON.stringify({ kind: "ack", channel: "command", sequence: turn.sequence, id: turn.commandId }));
    await until(() => storage.tasks.read(taskId)?.view.state === "running");
    peer.send(JSON.stringify({ kind: "event", sequence: 1, eventId: "first-approval", event: { kind: "approval", threadId, turnId, approvalId: "first-approval", callId: "first-call", name: "write", status: "pending", expiresAt: now + 60000 } }));
    await until(() => storage.tasks.read(taskId)?.view.state === "waiting_for_approval");
    const final = { kind: "event", sequence: 2, eventId: "final", event: { kind: "commit", threadId, turnId, messageId: "answer", blocks: [{ type: "paragraph", text: "Verified" }] } };
    peer.send(JSON.stringify(final));
    await until(() => storage.tasks.read(taskId)?.view.state === "completed");
    peer.send(JSON.stringify(final));
    await until(() => incoming.filter((frame) => frame.kind === "ack" && frame.id === "final").length === 2);
    const read = await (await request(`/tasks/${taskId}`)).json() as { view: { state: string; currentRun: { runId: string }; notification: unknown }; events: unknown[] };
    expect(read.view).toMatchObject({ state: "completed", currentRun: { runId: turnId }, notification: { taskId } });
    expect(read.events).toHaveLength(4);
    expect(storage.tasks.read(taskId)?.view.waitingOn).toBeUndefined();
    expect(frames.filter((frame) => frame.type === "bot_task_updated").at(-1)).toMatchObject({ view: read.view });
    expect((await request(`/tasks/${taskId}/retry`, { idempotencyKey: "late" })).status).toBe(409);
    expect((await request("/bots/sage/chat/messages", { text: "Pause this work" })).status).toBe(202);
    await until(() => incoming.filter((frame) => frame.kind === "command" && frame.command.kind === "turn").length === 2);
    const pausing = incoming.filter((frame) => frame.kind === "command" && frame.command.kind === "turn").at(-1);
    if (pausing?.kind !== "command" || pausing.command.kind !== "turn") throw new Error("missing second turn");
    peer.send(JSON.stringify({ kind: "ack", channel: "command", sequence: pausing.sequence, id: pausing.commandId }));
    const pauseRunId = pausing.command.turnId;
    const pauseTask = storage.tasks.list({ bot: "sage" }).find((view) => view.currentRun.runId === pauseRunId)!;
    await until(() => storage.tasks.read(pauseTask.taskId)?.view.state === "running");
    peer.send(JSON.stringify({ kind: "event", sequence: 3, eventId: "approval", event: { kind: "approval", threadId: pausing.command.threadId, turnId: pausing.command.turnId, approvalId: "approval", callId: "call", name: "write", status: "pending", expiresAt: Date.now() + 60000 } }));
    await until(() => storage.tasks.read(pauseTask.taskId)?.view.state === "waiting_for_approval");
    expect((await request(`/tasks/${pauseTask.taskId}/pause`, { idempotencyKey: "pause" })).status).toBe(200);
    await until(() => incoming.some((frame) => frame.kind === "command" && frame.command.kind === "interrupt"));
    peer.send(JSON.stringify({ kind: "event", sequence: 4, eventId: "paused", event: { kind: "interrupted", threadId: pausing.command.threadId, turnId: pausing.command.turnId, messageId: "paused" } }));
    await until(() => incoming.some((frame) => frame.kind === "ack" && frame.id === "paused"));
    expect(storage.tasks.read(pauseTask.taskId)?.view.state).toBe("waiting_for_user_input");
    expect((await request(`/tasks/${pauseTask.taskId}/resume`, { idempotencyKey: "resume" })).status).toBe(200);
    await until(() => incoming.filter((frame) => frame.kind === "command" && frame.command.kind === "turn").length === 3);
    const resumed = incoming.filter((frame) => frame.kind === "command" && frame.command.kind === "turn").at(-1);
    if (resumed?.kind !== "command" || resumed.command.kind !== "turn") throw new Error("missing resumed turn");
    peer.send(JSON.stringify({ kind: "ack", channel: "command", sequence: resumed.sequence, id: resumed.commandId }));
    await until(() => storage.tasks.read(pauseTask.taskId)?.view.state === "running");
    peer.send(JSON.stringify({ kind: "event", sequence: 5, eventId: "owner-approval", event: { kind: "approval", threadId: resumed.command.threadId, turnId: resumed.command.turnId, approvalId: "owner-approval", callId: "owner-call", name: "write", status: "pending", expiresAt: now + 180000 } }));
    await until(() => storage.tasks.read(pauseTask.taskId)?.view.state === "waiting_for_approval");
    peer.close(); await once(peer, "close"); await until(() => presence === "absent");
    now += 120000;
    expect(storage.tasks.read(pauseTask.taskId)?.view.state).toBe("blocked");
    now += 60000;
    storage.tasks.read(pauseTask.taskId);
    expect(storage.nativeInteraction("sage", "approval", "owner-approval")?.status).toBe("expired");
    peer = new WebSocket(`ws://127.0.0.1:${address.port}/attach/v1`, { headers: { authorization: "Bearer peer-secret" } });
    const reattached: AttachV1ServerFrame[] = [];
    peer.on("message", (data) => reattached.push(JSON.parse(String(data)) as AttachV1ServerFrame));
    await once(peer, "open");
    peer.send(JSON.stringify({ kind: "hello", version: 2, instanceId: "reattached", capabilities: ["draft", "tools", "approvals"], resume: { eventSequence: 5, commandSequence: resumed.sequence } }));
    await until(() => reattached.some((frame) => frame.kind === "hello_ack"));
    expect(storage.tasks.read(pauseTask.taskId)?.view).toMatchObject({ state: "running" });
    expect(storage.tasks.read(pauseTask.taskId)?.view.waitingOn).toBeUndefined();
  } finally { peer.close(); ingress.close(); plane.close(); await new Promise<void>((resolve) => server.close(() => resolve())); storage.close(); }
});
